[build]
  publish = "."
  command = ""

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "SENDCLOUD_SECRET_KEY,STRIPE_SECRET_KEY,SENDCLOUD_PUBLIC_KEY"

[functions]
  directory = "backend/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
